name: Run Herald Bluesky Bot

on:
  schedule:
    - cron: '15,45 * * * *'  # Runs at 15 and 45 minutes past every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 atproto python-dotenv pytz

      - name: Run Herald Bluesky Bot
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
        run: python herald_bluesky_bot.py

      - name: Commit posted URLs
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add posted_urls.txt || echo "No files to add"
          git commit -m "Update posted_urls.txt" || echo "No changes to commit"
          # Pull remote changes to avoid conflicts
          git fetch origin
          git pull origin main --rebase || echo "Failed to rebase, continuing with local changes"
          git push || echo "No changes to push"
