name: Run Herald Twitter Bot

on:
  schedule:
    - cron: '15,45 * * * *'  # Runs at 15 and 45 minutes past every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 tweepy python-dotenv pytz lxml

      - name: Run Herald Twitter Bot
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python herald_bot.py

      - name: Commit posted URLs
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          touch posted_urls_twitter.txt
          git add posted_urls_twitter.txt || echo "No files to add"
          git commit -m "Update posted_urls_twitter.txt" || echo "No changes to commit"
          git push || echo "No changes to push"
